### ISSUE TITLE
Move ABL to database.

### ISSUE THREAD

**Issue by ckline-tryptic** [openstax/corgi#496]
# Story
CM's want a more streamlined way to manage the ABL.

# Description
Currently editing the ABL in JSON format on github is tedious and error prone it would be good if the process could be automated and the data could exist in a more queryable form. 

# Acceptance Criteria
ABL has migrated over to to a database in CORGI alongside the jobs to facilitate a more automated management of accepted book versions.

# TODO
- [X] Design database
- [x] Create sqlalchemy model
- [x] Migrate ABL
- [ ] Create pydantic schema
- [ ] Create fastapi API
- [ ] There should be an add to ABL button
- [ ] This button should make sure the person is a CM or member of CE-Admin or the CE team (including styles)
- [ ] The button should also make the repo that is added public and turn on github pages.

**Comment by ckline-tryptic** [comment]
# Story
CM's want a more streamlined way to manage the ABL.

## Description
Currently editing the ABL in JSON format on github is tedious and error prone it would be good if the process could be automated and the data could exist in a more queryable form. 

## Acceptance Criteria
ABL has migrated over to to a database in CORGI alongside the jobs to facilitate a more automated management of accepted book versions.

- [X] Design database
- [ ] Create sqlalchemy model
- [ ] Migrate ABL
- [ ] Create pydantic schema
- [ ] Create fastapi API
- [ ] Integrate ABL with frontend

**Comment by TylerZeroMaster** [comment]
# New dialog subsection
## GIVEN
* Latest CORGI deploy on staging
* A successful web preview job
## WHEN
* The job details dialog is opened
## THEN
* There is a new section of the dialog for approving the books contained in the job

# Can add books when you have permission
## GIVEN
* The above
* You have adequate permission to approve a book
## WHEN
* You click the approve button on a book that is not on the ABL (job not highlighted)
## THEN
* The new version is added
* The version on https://openstax.org/rex/release.json remains

# Get a descriptive error if you do not have permission
## GIVEN
* The above
* You do not have adequate permission to approve a book
## WHEN
* You click the approve button on a book that is not on the ABL (job not highlighted)
## THEN
* You get a descriptive error message

**Comment by omehes** [comment]
testing: latest corgi update
job id dialog changed
selection of versions to add to abl in web preview jobs
added book raw gets green
test1 - ok
test2 - ok
test3 -
